
---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
defaultZone: http://localhost:8010/eureka/

---
# Ivr Default Values
A_APP_VERSION=0.1
default_attributes:
 #APP version
 A_APP_VERSION=0.2
 
 # Media server IP
 A_MEDIA_SERVER_IP=192.168.10.184
 A_MEDIA_SERVER_PORT=7000
 
 # Standard Prompts Path
 A_STANDARD_PROMPTS_URL=/CVP/audio/HOV_INB_CVP/std/
 
 # Custom Prompts Path
 A_CUSTOM_PROMPTS_URL=/CVP/audio/HOV_INB_CVP/app/
 
 # Maximum Tries - Combined Tries 
 A_MAX_TRIES=3
 A_MAX_REPEAT_TRIES=3

 # set to 1 as combined tries to be used
 A_MAX_NO_INPUT=1
 A_MAX_NO_MATCH=1

 # No Input Time out
 A_NO_INPUT_TIMEOUT=5s

 # No Match Audio
 A_NO_MATCH_AUDIO=5019.wav
 A_SPA_NO_MATCH_AUDIO=5019_SPA.wav

 # No Input Audio
 A_NO_INPUT_AUDIO=5018.wav
 A_SPA_NO_INPUT_AUDIO=5018_SPA.wav
 
 
 S_SILENCE_AUDIO_FILE=silence.wav
 ############### REPORTING PURPOSE####################################################
 #If strReportWTFlag(S_REPORT_WT_FLAG) is "N", Wait time XML packet will not be built
 #
 #If strReportWTFlag(S_REPORT_WT_FLAG) is "Y", Wait time XML packet will be built.
 #####################################################################################

 S_REPORT_WT_FLAG=N


